Update landing_actions.yml

diff --git a/.github/workflows/landing_actions.yml b/.github/workflows/landing_actions.yml
--- a/.github/workflows/landing_actions.yml
+++ b/.github/workflows/landing_actions.yml
@@ -17,10 +17,10 @@ jobs:
         run: npm i
       - name: build landing
         run: npm run build
-      - name: serve landing
-        run: pm2 start npm -- start
-      - name: rename landing in pm2
-        run: pm2 restart npm --name landing
+      # - name: serve landing
+      #   run: pm2 start npm -- start
+      # - name: rename landing in pm2
+      #   run: pm2 restart npm --name landing
       - name: Install SSH Key
         uses: shimataro/ssh-key-action@v2
         with:
@@ -28,10 +28,12 @@ jobs:
           known_hosts: 'unnecessary'
       - name: Adding Known Hosts
         run: ssh-keyscan -H ${{ secrets.SSH_LANDING_HOST }} >> ~/.ssh/known_hosts
-      - name: Error Handling
-        run: |
-          pm2_status=$?
-          if [ $pm2_status -ne 0 ]; then
-            echo "Failed to start PM2. Exiting..."
-            exit $pm2_status
-          fi
+      - name: Print Message
+        run: echo "Workflow completed successfully!"
+      # - name: Error Handling
+      #   run: |
+      #     pm2_status=$?
+      #     if [ $pm2_status -ne 0 ]; then
+      #       echo "Failed to start PM2. Exiting..."
+      #       exit $pm2_status
+      #     fi
